# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-09 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20170409_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketerprofile',
            name='qualification',
        ),
        migrations.AddField(
            model_name='marketerprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='pimpuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='GB', max_length=2),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
